language: node_js

node_js:
  - "4.2.3"

before_install:
  - sudo apt-get update
  - sudo apt-get install libxss1 libappindicator1 libindicator7 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - npm install -g karma
  - npm install -g bower
  - npm install -g protractor

before_script:
  - webdriver-manager update
  - npm install
  - bower install

install:
  - sudo pip install -r requirements-devel.txt

script:
  - ./runtests.sh
